"""Attribute-link presence predicates.

Each attribute kind (description, signature, statements, references,
name, label) carries the same shape: F=[doc], G=[sidecar]. The
predicates over them follow three templates — presence, sidecar
lookup, freshness — generated by `lib/predicates/factory.py`. This
module just instantiates them per kind.

Version-bearing addresses (VER3) make alignment questions like "does
the head version of claim D have an active description link?" reduce
to a single substrate query. When the claim revises (D → D.1), an
existing description link still points at D — the predicate returns
False for D.1 until the corresponding producer runs against it.

Freshness predicates compare supersession chain lengths: each
`register_version` advances the relevant chain by 1; chain length
counts as "edit count" (claim) or "attestation count" (sidecar).
Equal counts mean every claim edit has a matching sidecar
attestation. Lower sidecar count means at least one edit is
unattested → stale.
"""

from __future__ import annotations

from .factory import (
    attribute_is_fresh, attribute_sidecar, has_attribute,
)


# ─── Presence ──────────────────────────────────────────────────────

has_description = has_attribute("description")
has_signature   = has_attribute("signature")
has_statements  = has_attribute("statements")
has_name        = has_attribute("name")
has_label       = has_attribute("label")


# ─── Sidecar lookup ────────────────────────────────────────────────

description_sidecar_of = attribute_sidecar("description")
signature_sidecar_of   = attribute_sidecar("signature")
statements_sidecar_of  = attribute_sidecar("statements")
references_sidecar_of  = attribute_sidecar("references")


# ─── Freshness (chain comparison) ──────────────────────────────────

description_is_fresh = attribute_is_fresh("description")
signature_is_fresh   = attribute_is_fresh("signature")
references_is_fresh  = attribute_is_fresh("references")

# Statements fires only at "settled" boundaries (no open revises +
# last 2 consecutive reviews came back clean — matches the n=2
# stochastic-quiescence floor used by note_review). For a note that
# absorbs many cycles, this collapses to one extraction per N+1
# lifecycle. Without n=2 here, the optimistic 1-clean gate causes
# premature extraction that gets invalidated by the next revise
# cycle.
statements_is_fresh = attribute_is_fresh(
    "statements", confirmation_gate=True, confirmation_n=2,
)
