#!/usr/bin/env python3
"""
Mechanical dependency checker for ASN rebase.

Reads the ASN's deps YAML (generated by rebase_deps.py) and cross-references
against dependency exports to find:
  1. Stale labels — follows_from references labels that don't exist in any dependency
  2. Missing deps — ASN prose cites foundation labels not in the deps YAML
  3. Undeclared cross-ASN — ASN references an ASN not in manifest depends

No LLM required. Deterministic.

Usage:
    python scripts/lib/rebase_mechanical.py 43
    python scripts/lib/rebase_mechanical.py 43 --verbose
"""

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from paths import WORKSPACE, STATEMENTS_DIR, PROJECT_MODEL_DIR, load_manifest
from lib.common import find_asn

# Import label scanning from dependency-audit.py (hyphenated filename)
import importlib
_dep_audit_path = WORKSPACE / "scripts" / "dependency-audit.py"
_spec = importlib.util.spec_from_file_location("dependency_audit", _dep_audit_path)
_dep_audit = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_dep_audit)
build_label_map = _dep_audit.build_label_map
scan_reasoning_doc = _dep_audit.scan_reasoning_doc
get_dep_chain = _dep_audit.get_dep_chain


@dataclass
class Finding:
    category: str   # "stale-label", "missing-dep", "undeclared-asn", "prose-only"
    label: str
    source_asn: int | None
    location: str   # e.g., "deps:GlobalUniqueness" or "prose"
    detail: str


def load_deps_yaml(asn_num):
    """Load the deps YAML for an ASN. Returns dict or None."""
    path = STATEMENTS_DIR / f"ASN-{asn_num:04d}-deps.yaml"
    if not path.exists():
        return None
    with open(path) as f:
        return yaml.safe_load(f)


def check_stale_labels(deps, label_map, dep_chain):
    """Check 1: every label in follows_from must exist in a dependency's export.

    Labels that are local (defined in the same ASN's deps) are OK.
    Labels from dependency ASNs must appear in their exports.
    """
    findings = []
    asn_num = deps["asn"]

    # Build set of local labels (defined in this ASN)
    local_labels = set(deps["properties"].keys())

    for prop_label, prop_data in deps["properties"].items():
        for ref_label in prop_data.get("follows_from", []):
            # Local reference — OK
            if ref_label in local_labels:
                continue

            # Check if label exists in any dependency's export
            if ref_label in label_map:
                source = label_map[ref_label]
                if source not in dep_chain and source != asn_num:
                    findings.append(Finding(
                        category="undeclared-asn",
                        label=ref_label,
                        source_asn=source,
                        location=f"deps:{prop_label}",
                        detail=f"Property {prop_label} references {ref_label} "
                               f"from ASN-{source:04d}, which is not in depends "
                               f"(declared: {deps['depends']})"
                    ))
            else:
                findings.append(Finding(
                    category="stale-label",
                    label=ref_label,
                    source_asn=None,
                    location=f"deps:{prop_label}",
                    detail=f"Property {prop_label} references {ref_label} "
                           f"which does not exist in any active ASN's export"
                ))

        # Check extends/parallels references
        for rel_type in ("extends", "parallels"):
            rel = prop_data.get(rel_type)
            if not rel:
                continue
            ref_label = rel.get("label", "")
            ref_asn = rel.get("asn")
            if ref_label and ref_label not in label_map:
                findings.append(Finding(
                    category="stale-label",
                    label=ref_label,
                    source_asn=ref_asn,
                    location=f"deps:{prop_label}.{rel_type}",
                    detail=f"Property {prop_label} {rel_type} {ref_label} "
                           f"which does not exist in any active ASN's export"
                ))
            if ref_asn and ref_asn not in dep_chain:
                findings.append(Finding(
                    category="undeclared-asn",
                    label=ref_label,
                    source_asn=ref_asn,
                    location=f"deps:{prop_label}.{rel_type}",
                    detail=f"Property {prop_label} {rel_type} references "
                           f"ASN-{ref_asn:04d} which is not in depends"
                ))

    return findings


def check_prose_citations(asn_num, deps, label_map, dep_chain):
    """Check 2: ASN prose cites foundation labels not in the deps YAML.

    Find labels referenced in the prose that come from dependency ASNs
    but are not declared in the property table's follows_from.
    """
    findings = []
    asn_path, _ = find_asn(str(asn_num))
    if asn_path is None:
        return findings

    # Get all labels referenced in prose
    prose_refs = scan_reasoning_doc(asn_path, label_map)

    # Build the set of all labels declared in deps YAML follows_from
    declared_labels = set()
    for prop_data in deps["properties"].values():
        declared_labels.update(prop_data.get("follows_from", []))
        for rel_type in ("extends", "parallels"):
            rel = prop_data.get(rel_type)
            if rel and rel.get("label"):
                declared_labels.add(rel["label"])

    # Also include local labels
    local_labels = set(deps["properties"].keys())

    for ref_label, source_asn in prose_refs.items():
        # Skip if it's a local label
        if ref_label in local_labels:
            continue

        # Skip if it's from the ASN itself
        if source_asn == asn_num:
            continue

        # Skip if it's already declared in deps YAML
        if ref_label in declared_labels:
            continue

        # Skip if it's not from a dependency (could be a different context)
        if source_asn not in dep_chain:
            continue

        findings.append(Finding(
            category="prose-only",
            label=ref_label,
            source_asn=source_asn,
            location="prose",
            detail=f"Prose cites {ref_label} (ASN-{source_asn:04d}) "
                   f"but no property table entry lists it in follows_from"
        ))

    return findings


def check_asn(asn_num, verbose=False):
    """Run all mechanical checks on an ASN. Returns list of Findings."""
    deps = load_deps_yaml(asn_num)
    if deps is None:
        print(f"  [ERROR] No deps YAML for ASN-{asn_num:04d} — "
              f"run: python scripts/lib/rebase_deps.py {asn_num}",
              file=sys.stderr)
        return None

    label_map, _ = build_label_map()
    dep_chain = get_dep_chain(asn_num)

    if verbose:
        print(f"  [INFO] ASN-{asn_num:04d}: {len(deps['properties'])} properties, "
              f"depends: {deps['depends']}, dep chain: {sorted(dep_chain)}",
              file=sys.stderr)
        print(f"  [INFO] Label map: {len(label_map)} labels across active ASNs",
              file=sys.stderr)

    findings = []

    # Check 1: stale labels and undeclared ASN references
    findings.extend(check_stale_labels(deps, label_map, dep_chain))

    # Check 2: prose citations not in deps YAML
    findings.extend(check_prose_citations(asn_num, deps, label_map, dep_chain))

    return findings


def format_findings(findings):
    """Format findings as markdown for open-issues.md."""
    if not findings:
        return ""

    lines = []
    for i, f in enumerate(findings, 1):
        asn_ref = f" (ASN-{f.source_asn:04d})" if f.source_asn else ""
        lines.append(f"### Finding {i}: [{f.category}] {f.label}{asn_ref}")
        lines.append(f"**Location**: {f.location}")
        lines.append(f"**Detail**: {f.detail}")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Mechanical dependency checker for ASN rebase")
    parser.add_argument("asn", help="ASN number (e.g., 43)")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    asn_num = int(re.sub(r"[^0-9]", "", args.asn))
    findings = check_asn(asn_num, verbose=args.verbose)

    if findings is None:
        sys.exit(1)

    if findings:
        print(format_findings(findings))
        print(f"  [{len(findings)} findings]", file=sys.stderr)
    else:
        print(f"  [CLEAN] No mechanical findings for ASN-{asn_num:04d}",
              file=sys.stderr)


if __name__ == "__main__":
    main()
